// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApLx1os-bzg1koYBxPivnfQkJ5O0bnU50',
    appId: '1:450708487263:web:2838cbb9bf0fd2a7482fea',
    messagingSenderId: '450708487263',
    projectId: 'evalemili',
    authDomain: 'evalemili.firebaseapp.com',
    databaseURL: 'https://evalemili-default-rtdb.firebaseio.com',
    storageBucket: 'evalemili.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyEKm_SM9VygWBcWOZSr_32jeKrvG811U',
    appId: '1:450708487263:android:4c6d3404dbd7c6c8482fea',
    messagingSenderId: '450708487263',
    projectId: 'evalemili',
    databaseURL: 'https://evalemili-default-rtdb.firebaseio.com',
    storageBucket: 'evalemili.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCFU3yxlP9Am3XzGe-UIbZROvViZXLKxg',
    appId: '1:450708487263:ios:e219f772c9206e68482fea',
    messagingSenderId: '450708487263',
    projectId: 'evalemili',
    databaseURL: 'https://evalemili-default-rtdb.firebaseio.com',
    storageBucket: 'evalemili.firebasestorage.app',
    iosBundleId: 'com.example.kitchenOrchestrator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCFU3yxlP9Am3XzGe-UIbZROvViZXLKxg',
    appId: '1:450708487263:ios:e219f772c9206e68482fea',
    messagingSenderId: '450708487263',
    projectId: 'evalemili',
    databaseURL: 'https://evalemili-default-rtdb.firebaseio.com',
    storageBucket: 'evalemili.firebasestorage.app',
    iosBundleId: 'com.example.kitchenOrchestrator',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApLx1os-bzg1koYBxPivnfQkJ5O0bnU50',
    appId: '1:450708487263:web:c448f3b37b9af7c9482fea',
    messagingSenderId: '450708487263',
    projectId: 'evalemili',
    authDomain: 'evalemili.firebaseapp.com',
    databaseURL: 'https://evalemili-default-rtdb.firebaseio.com',
    storageBucket: 'evalemili.firebasestorage.app',
  );

}